### ISSUE TITLE
Tooltip is clipped

### ISSUE THREAD

**Issue by ildar170975** [alexarch21/history-explorer-card#107]
A tooltip is clipped on the bottom:
```
type: custom:history-explorer-card
defaultTimeRange: 24h
graphs:
  - type: timeline
    entities:
      - entity: sun.sun
header: full
uiLayout:
  toolbar: hide
  selector: hide
tooltip:
  size: full
```
![image](https://user-images.githubusercontent.com/71872483/207496570-4eb3dad3-5c6b-4a0e-9bcc-78dffa0f33ed.png)

HA 2022.12.5, default theme
HISTORY-EXPLORER-CARD  Version 1.0.40
