### ISSUE TITLE
[FR] Allow hiding a name in a tooltip for timelines

### ISSUE THREAD

**Issue by ildar170975** [alexarch21/history-explorer-card#108]
Unable to hide a name in a tooltip:
```
type: custom:history-explorer-card
graphs:
  - type: timeline
    entities:
      - entity: sun.sun
tootip:
  showLabel: false
```
![image](https://user-images.githubusercontent.com/71872483/207497359-f0ddfc3d-33d9-490c-8a0f-6a69d79c1e2e.png)

Contrary, a name cannot be shown in a tooltip if it is not shown on a card:
```
type: custom:history-explorer-card
graphs:
  - type: timeline
    entities:
      - entity: sun.sun
tootip:
  showLabel: true
labelsVisible: false
```
![image](https://user-images.githubusercontent.com/71872483/207497802-55c70805-3972-497d-86e5-f023f178119f.png)

HA 2022.12.5, default theme
HISTORY-EXPLORER-CARD Version 1.0.40
