### ISSUE TITLE
[qiestion] Why keeping a huge list of entities in DOM by default?

### ISSUE THREAD

**Issue by ildar170975** [alexarch21/history-explorer-card#109]
Currently by default DOM contains a really huge list of elements:

![image](https://user-images.githubusercontent.com/71872483/207498787-30259ed8-6450-4a30-a49c-9392fb90b787.png)

Is it really required to have it by default?
Should we change a default mask for a selector to kind of "none" (i.e. none entities are selected)? It could be confusing but may (not sure) save some resources.

Test code:
```
type: custom:history-explorer-card
defaultTimeRange: 24h
graphs:
  - type: timeline
    entities:
      - entity: sun.sun
uiLayout:
  toolbar: hide
  selector: hide
```
![image](https://user-images.githubusercontent.com/71872483/207499682-0b46e9d5-049f-4494-8e20-3225a431ae61.png)

Also, if currently selector is hidden - then may be these elements should not be here at all?

Could it a be a reason of slow processing of the card?
Any small change in HA Editor causes a freeze for ~10 sec - even with `sun.sun` for 24h.
