### ISSUE TITLE
Entities missing with recordedEntitiesOnly: true

### ISSUE THREAD

**Issue by VDRainer** [alexarch21/history-explorer-card#11]
I have 6 Dallas Temperature sensors that show recorded data in the graph and also in the dropdown.
![20220131_223722](https://user-images.githubusercontent.com/26381449/151878050-4f6f1993-03e0-4a3a-8b66-efd18155fe6b.png)
If i enable recordedEntitiesOnly
```
      - type: custom:history-explorer-card
        recordedEntitiesOnly: true
```
only two of the sensors are in the dropdown list.
![20220131_224037](https://user-images.githubusercontent.com/26381449/151878288-102c0a4c-2364-4b78-b2ba-c2a43fad3a2c.png)
These two sensors are also added to the default HA History.
```
history:
  use_include_order: true
  include:
    entities:
      - sensor.ds18b20_02
      - sensor.ds18b20_04
      - ...
```
If i remove them from the history configuration the dropdown is empty.
So are the entities selected from the history and not from the recorder?

Thanks for this beautifull card!
