### ISSUE TITLE
[optimization] Do not add a list of entities into DOM if "selector: hide"

### ISSUE THREAD

**Issue by ildar170975** [alexarch21/history-explorer-card#110]
Based on this comment: https://github.com/alexarch21/history-explorer-card/issues/109#issuecomment-1350350206

Suggest NOT to add the entities list into DOM when selector is hidden.

Currently the list is added:
```
type: custom:history-explorer-card
defaultTimeRange: 24h
graphs:
  - type: timeline
    entities:
      - entity: sun.sun
uiLayout:
  toolbar: hide
  selector: hide
```
![image](https://user-images.githubusercontent.com/71872483/207501854-c735645c-a0cf-421f-83c0-e407210259fe.png)

![image](https://user-images.githubusercontent.com/71872483/207501840-0041b3e9-b5bc-4119-badf-af91c1097596.png)
