### ISSUE TITLE
Dynamically added entity is added to every card

### ISSUE THREAD

**Issue by ildar170975** [alexarch21/history-explorer-card#111]
Assume a view containing several cards:
```
  - theme: Backend-selected
    title: chart-3
    path: chart-3
    badges: []
    cards:
      - type: custom:history-explorer-card
        defaultTimeRange: 24h
        graphs:
          - type: timeline
            entities:
              - entity: sun.sun
        uiLayout:
          toolbar: hide
          selector: hide
        filterEntities: undefined

      - type: custom:history-explorer-card
        defaultTimeRange: 24h
        graphs:
          - type: timeline
            entities:
              - entity: sun.sun
```
![изображение](https://user-images.githubusercontent.com/71872483/207534641-8dcd80fa-6bb3-4821-9688-533f66126a96.png)

If some entity is added for the 2nd card - then it is displayed for every card:
![изображение](https://user-images.githubusercontent.com/71872483/207534948-cf02d58d-f039-4ed8-9c6d-892a184701f5.png)

I believed a dynamically added entity is supposed to be displayed only on the card where it was added.
