### ISSUE TITLE
coloring bars according to value doesn't work for yaml graphs

### ISSUE THREAD

**Issue by think-nice-things** [alexarch21/history-explorer-card#123]
Hi,

I can't get coloring of bars according to the value working when defining graphs with yaml.
Graphs added dynamically are working though.

Here's my example: the first graph is defined with yaml.
Both displayed sensors  belong to the device class "wind_speed".
The top graph is defined with yaml, the bottom graph added dynamically.
Any ideas?

```
type: custom:history-explorer-card
cardName: wetter-aalen-test
entityOptions:
  wind_speed:
    type: bar
    color:
      '2': green
      '4': yellow
      '6': red
graphs:
  - type: bar
    entities:
      - entity: sensor.aalbaeumle_wind_speed
```

![image](https://user-images.githubusercontent.com/4885370/210736287-d31afa87-b89e-42fe-8fe8-3a51ec38cdeb.png)
