### ISSUE TITLE
timeline mode deesn't work for me

### ISSUE THREAD

**Issue by areyoufserious** [alexarch21/history-explorer-card#14]
Hi
i"m trying to add non-sersor entities, but i can't see chart 
i tried binary sensors, humidifier, heater, tried manual mode and selector mode -- result is the same
however charts work great for sensor entities like temperature, what i do wrong?

**Comment by alexarch21** [comment]
Please post your YAML

**Comment by areyoufserious** [comment]
sure
```
type: custom:history-explorer-card
cardName: historycard-75274398
uiLayout:
  toolbar: hide
  selector: hide
header: ' '
uimode: dark
showUnavailable: true
entityOptions:
  temperature:
    color: rgb(255, 0, 78)
    fill: rgba(255, 0, 78, 0.4)
  humidity:
    color: rgb(3, 155, 229)
    fill: rgba(3, 155, 229, 0.4)
  pressure:
    color: rgb(0, 255, 8)
    fill: rgba(0, 255, 8, 0.4)
graphs:
  - type: line
    entities:
      - entity: sensor.0x158d000410b3a8_temperature
        color: rgb(255, 0, 78)
        fill: rgba(255, 0, 78, 0.4)
        name: Sensor?
        width: 4
      - entity: sensor.zhimi_zb1_057c_temperature
        color: rgb(255, 0, 0)
        fill: rgba(255, 0, 0, 0.4)
        name: Smartmi Heater
        width: 4
  - type: timeline
    entities:
      - entity: humidifier.mi_smart_humidifer_humidifier
        color: rgb(3, 155, 229)
        fill: rgba(3, 155, 229, 0.4)
        name: humidifier
        width: 4
```


Also when i add timeline block, it affects all chart
![card1](https://user-images.githubusercontent.com/77510096/152247107-f00475f2-0222-41c0-950a-c39a4a302421.png)

Without timeline:

![card2](https://user-images.githubusercontent.com/77510096/152247232-9814d7db-d74b-409a-9eab-9b3a96500006.png)
