### ISSUE TITLE
Unable to add sensors via YAML

### ISSUE THREAD

**Issue by dpeet** [alexarch21/history-explorer-card#141]
Hey @alexarch21 !

First thanks for such an excellent addition to home assistant!  This card is packed with cool stuff.

I have been trying to add entities to the card via yaml, but I can't get anything to display, so I must have some syntax wrong.  I'm doing this so that the graphs shown remain the same when I use different computers / browsers to view home assistant.  Below is the yaml I have in the lovelace editor on the frontend.  If I add the sensors in the UI, they work as expected, so it seems to be the yaml that's the issue.

```yaml
type: custom:history-explorer-card
cardName: historycard-99116525
grahphs:
  - type: line
    entities:
      - entity: sensor.zone_1_temperature
      - entity: sensor.zone_2_temperature
      - entity: sensor.zone_3_temperature
recordedEntitiesOnly: true
showCurrentValues: true
combineSameUnits: true
refresh:
  automatic: true
```

Thanks!
