### ISSUE TITLE
Dynamically sorting entities / compatibility with auto-entities

### ISSUE THREAD

**Issue by R5fan** [alexarch21/history-explorer-card#143]
I use auto-entities a lot, for instance, one of my charts shows all door/window/motion sensors in a history chart ordered by most recently changed. With auto entities this is easy:
```
type: custom:auto-entities
card:
  type: history-graph
  state_color: true
  title: Geschiedenis
filter:
  include:
    - entity_id: '*iaszone*'
      sort:
        method: last_changed
        reverse: true
show_empty: false
```
 Which results in something like this:
![image](https://user-images.githubusercontent.com/1439530/219875000-fbade530-85d6-4b5e-9ec3-94b6d121ff96.png)

Im now moving everything over to history explorer card (HEC), in order to get all the options, scrolling etc, but I cant replicate or integrate the above. HEC has some functionality to auto fill and filter entities, but only for the interactive dropdown, which is of no use. (And honestly, I find this approach a bit weird and unwanted in general, as there is no way to view or edit a list of entities created this way, or customize elements of it, and if anyone clicks the little x mark, they are all gone. Just using YAML as default, or ideally with a GUI like default cards, would be way better IMHO.)

Even if I manually added all the sensors using YAML,  there is no way to sort entities by last_changed .

Ideally I could combine auto-entities with HEC, just like Im combining it with the default history-graph now, but the syntax requiring entities to be under the graph section make this impossible AFAICT.
