### ISSUE TITLE
`combineSameUnits: true` not honored using * in entity list in header with `recordedEntitiesOnly: true`

### ISSUE THREAD

**Issue by GrizzlyAK** [alexarch21/history-explorer-card#163]
It appears that the `combineSameUnits: true` is not honored when using `*` in entity list in header with `recordedEntitiesOnly: true`, like it does if I enter other wildcards, such as `*temperature*`.

The following is the Card YAML.
```
type: custom:history-explorer-card
cardName: history-panel-view
recordedEntitiesOnly: true
lineMode: stepped
showCurrentValues: true
defaultTimeRange: 14d
combineSameUnits: true
uimode: dark
labelAreaWidth: 300
refresh:
  automatic: true
  interval: 30
uiLayout:
  selector: top
  toolbar: both
  sticky: top
uiColors:
  labels: lime
```
Below is a screenshot of the single graph displayed when I enter `*temperature*` in the entity list (note: I retyped the wildcard in the entity list to show what I added).

![image](https://user-images.githubusercontent.com/4411963/227820396-52a0bffd-e740-4018-9bc1-f0ce005bcc4a.png)

Below is a screenshot of a section of the LONG list of graphs on the page when I enter a `*` in the entity list. As you can see, there are multiple  °F plots, multiple lx plots, etc, instead of them being combined. I would expect them to be combined charts like the one above.

![image](https://user-images.githubusercontent.com/4411963/227820661-42db95a6-bf5b-408b-84d0-5024e1c62fd0.png)
