### ISSUE TITLE
Feature Request: optionally display attribute rather than state

### ISSUE THREAD

**Issue by bennop** [alexarch21/history-explorer-card#165]

**Comment by alexarch21** [comment]
Attribute support is not planned at this time, due to the way the HA database works it would incur a large performance penalty.

You can map an attribute to a state using a template sensor and graph that one instead.

**Comment by bennop** [comment]
Thank you for this hint - figured out how to do it and am happy for now ;-)

Keep up the good work!

For anybody who wonders how it is done:

I now have this in my `template.yaml` file:

```
- sensor:
    # make attribute ('current_temperature' from 'climate.fritz_dect_301_1') available as entity
    # through a template sensor
    - name: Current Temperature
      unit_of_measurement: "°C"
      state_class: measurement
      icon: mdi:thermometer
      state: >-
        {{ state_attr('climate.fritz_dect_301_1', 'current_temperature') }}
 ```
(Need to at least reload the template entities for it to show)
