### ISSUE TITLE
Feature Request:  Export all entities on graph

### ISSUE THREAD

**Issue by hanscomps** [alexarch21/history-explorer-card#168]
When "Export as CSV" only one (first added) values are exported.  
It will be great to have all the graph values be exported into one CSV.

**Comment by alexarch21** [comment]
I'm not sure I understand. Could you clarify this ?

**Comment by hanscomps** [comment]
Sure.
When enabling "combineSameUnits: true" I expect that "Export as CSV" will include all the values/entities on the graph, but I only see the "first" added entity in the CSV.   Maybe I am  missing something in settings? 
Mind you, trying now with multiple separate graphs I still only get a single entity in the CSV file?

**Comment by alexarch21** [comment]
The card exports all entities in all graphs that are currently visible in the card you triggered the export from.

Post your config YAML and the CSV export that was generated from it.

**Comment by hanscomps** [comment]
I ony added the "combineSameUnits" to the config.
Must mention this is a manual install of Home Assistant 2023.2.3, on Archlinux.

```
title: HomeCore
views:
  - theme: Backend-selected
    path: default_view
    title: Home
    type: panel
    badges: []
    cards:
      - type: custom:history-explorer-card
        cardName: historycard-42492743
        combineSameUnits: true

```

[entities-2023-04-27_13_11_05.csv](https://github.com/alexarch21/history-explorer-card/files/11342743/entities-2023-04-27_13_11_05.csv)

![Screenshot_20230427_131036](https://user-images.githubusercontent.com/16793558/234845805-71187542-6fbb-47ce-9308-530fd57e6e89.png)
