### ISSUE TITLE
Localization stopped working since 2023.4

### ISSUE THREAD

**Issue by ildar170975** [alexarch21/history-explorer-card#171]
Test card:
```
type: custom:history-explorer-card
cardName: history-card-040523_1
defaultTimeRange: 48h
graphs:
  - type: timeline
    entities:
      - entity: sun.sun
      - entity: binary_sensor.net_is_available_internet
      - entity: binary_sensor.testing_device_class_motion
      - entity: binary_sensor.testing_device_class_heat
      - entity: device_tracker.apple_watch_s4_asuswrt
stateTextMode: auto
tooltip:
  stateTextMode: auto
```
![изображение](https://user-images.githubusercontent.com/71872483/236080105-827e5024-b844-44e2-9536-05bb7c497ed6.png)

Since `stateTextMode: auto` localized values for states are expected:
- for values on graphs
- for values on tooltips
