### ISSUE TITLE
Question around state colors when state contains a space character

### ISSUE THREAD

**Issue by dan-simpson-zip** [alexarch21/history-explorer-card#180]
As part of your documetation I see the following

```
type: custom:history-explorer-card
stateColors:
  sensor.Dry: tan
  sensor.Wet: green
```

Works super well for most cases, but I'm trying to set the state color based off of an input select, which contains the following options:
- Off
- 'Heat up'
- 'Keep warm'
- 'Cool down'

Wondering how (if possible) I can set the colors for these, without changing the values themselves.  I've tried `input_select.Heat Up` `input_select.['Heat Up']` and `input_select.Heat+Up`, but no luck.  Guessing it might not be possible, but can't hurt to ask 🤷 🤞 

Thanks!
