### ISSUE TITLE
Why is my y-axis range always larger than expected? 

### ISSUE THREAD

**Issue by guidocioni** [alexarch21/history-explorer-card#186]
I really don't know if I'm missing something obvious here, but the range of the y-axis of my plots is always larger than expected and does not honor the min/max on the selected time period, which should be the expected behaviour according to the documentation.

<img width="1689" alt="Screen Shot 2023-06-26 at 11 32 03" src="https://github.com/alexarch21/history-explorer-card/assets/12760310/84be5221-d861-4dd1-bd1c-553acf89c777">

is there anyway to correct this behaviour? This enlarged range makes it really hard to visualise small changes.

**Comment by alexarch21** [comment]
Please post the YAML.

**Comment by guidocioni** [comment]
Ups, sorry, here you go

```yaml
type: custom:history-explorer-card
cardName: historycard-46415452
recordedEntitiesOnly: true
defaultTimeRange: 4h
combineSameUnits: true
lineMode: lines
showUnavailable: true
refresh:
  automatic: true
showCurrentValues: true
decimation: false
lineGraphHeight: 200
```
