### ISSUE TITLE
No x/y axis labels?   

### ISSUE THREAD

**Issue by fcassirer** [alexarch21/history-explorer-card#193]
Great card, thank you!

I just tried using it and I'm scratching my head as there seem to be no controls for the X/Y axis.  The default graph doesn't label them for me and all the examples show them but none of the accompanying YAML seem to explicitly enable them.

Here is my YAML:

```
type: custom:history-explorer-card
cardName: historycard-90178479
defaultTimeRange: 21d
combineSameUnits: true
entityOptions:
  ymin: 0
  ymax: 100
uiColors:
  gridlines: dimgray
```

I have two sensors added interactively, both are temperature related.

 
![Screenshot from 2023-08-01 13-22-22](https://github.com/alexarch21/history-explorer-card/assets/4642327/3ebd88a1-5967-437b-941f-7fb39f6b60f6)

I must be missing something ... thanks.
-Fred
