### ISSUE TITLE
Showing current sensor value not working

### ISSUE THREAD

**Issue by felixwelsch** [alexarch21/history-explorer-card#194]
Hi,
I am using the minimal example with the latest version of history-explorer-card and Home Assistant 2023.8.1:

```
type: custom:history-explorer-card
showCurrentValues: true
graphs:
  - type: line
    entities:
      - entity: sensor.temperature
```

And not seeing any value in the legend.

<img width="326" alt="Bildschirmfoto 2023-08-06 um 19 24 27" src="https://github.com/alexarch21/history-explorer-card/assets/28998101/e9086c4d-6287-4fa0-848a-5101a733c1de">

What i am doing wrong?

Thanks in advance
