### ISSUE TITLE
Provide ability to include entities by attributes

### ISSUE THREAD

**Issue by lhart-intelycare** [alexarch21/history-explorer-card#195]
My apologies if this feature is available already and I'm missing the documentation.

It would be great if you could include a set of entities by looking at their attributes.  Another card, auto-entities, handles this well:
```
type: custom:auto-entities
card:
  type: entities
  state_color: true
filter:
  include:
    - attributes:
        device_class: power
  exclude:
    - device_model: VUE002
    - name: '*Vue*'
sort:
  method: friendly_name
  reverse: false
  ignore_case: true
  numeric: true
```
I would love to see the same in this great graphical view.

Thanks!
