### ISSUE TITLE
Y-axis intervals

### ISSUE THREAD

**Issue by DaniJulia** [alexarch21/history-explorer-card#196]
First of all, congratulations for such amazing card! Using it every single day!
The ability to set the y-axis minimum and maximum values is particularly valuable in tailoring the visual representation of data; although currently, there isn't an option to define the scaling in-between. Having the ability to specify this interval would provide better and easier understanding of the variations in scenarios where the data range is so bounded to its granularity.
For instance, Temperature entities: If I can fix/set a line for every 1 degree, it will be very visual to quantify the temperature difference between 2 moments or between 2 different entities, simply by the lines in between, without having to care about how many degrees each line represents.

**Comment by alexarch21** [comment]
Was added to V1.0.48 !

Example:
```
graphs:
  - type: line
    options:
      ymin: 0           # optional
      ymax: 40        # optional
      ystepSize: 5
    entities:
      - entity: sensor.outdoor_temperature
```
