### ISSUE TITLE
I don't get why the display looks like this

### ISSUE THREAD

**Issue by commentsonly** [alexarch21/history-explorer-card#203]
Got 3 shelly plus 1pm set up same way, same firmware same HA integration.
The drive a 3 phase heater

The phase get enabled depending upon the overproduction.

First pic does show a strange behaviour for phase L3.
When this gets enabled it does result in getting a curve while until it go enabled the history and the state of this L3 is 0.
Means I expected a visualization similar to the red and yellow line.
When looking at the entity itself (pic2) it shows the expected rectangle behaviour.
any idea?
![Screenshot 2023-09-11 111236](https://github.com/alexarch21/history-explorer-card/assets/35866491/3e9b7d53-58f3-4211-bb80-87b476c4e98b)
![Screenshot 2023-09-11 111324](https://github.com/alexarch21/history-explorer-card/assets/35866491/64a5278b-8c7b-4105-9b35-627c615c05ed)

definition of the card section got nothing special.
```
  - type: line
    entities:
      - entity: sensor.p1pm_heizstab_l1_power
        color: '#ff0000'
      - entity: sensor.p1pm_heizstab_l2_power
        color: '#ffff00'
      - entity: sensor.p1pm_heizstab_l3_power
        color: '#00ff00'
```
