### ISSUE TITLE
Auto Refresh on timeline does not seem to work after first refresh

### ISSUE THREAD

**Issue by slhad** [alexarch21/history-explorer-card#206]
When I configure charts with timeline, the autorefresh does not seem to happen.

After trying to reproduce it, it seems that the refresh occur only once and then stop.

Am I missing something ?

YML to reproduce it with one simple input button

```
type: vertical-stack
cards:
  - type: history-graph
    hours_to_show: 1
    entities:
      - entity: input_boolean.isstreaming
  - type: custom:history-explorer-card
    cardName: advanced-history-tests
    header: hide
    defaultTimeRange: 1h
    uiLayout:
      toolbar: hide
      selector: hide
    refresh:
      automatic: true
      interval: 30
    graphs:
      - type: timeline
        entities:
          - entity: input_boolean.isstreaming
```

<img width="255" alt="image" src="https://github.com/alexarch21/history-explorer-card/assets/4113601/a5af05e0-9fb9-4075-9292-933cab284ae5">
