### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by mobiledude** [alexarch21/history-explorer-card#207]
getting a strange error:
```
Logger: frontend.js.latest.202309280
Source: components/system_log/__init__.py:300
First occurred: 21:45:26 (1 occurrences)
Last logged: 21:45:26

Uncaught error from Chrome 117.0.0.0 on Mac OS 10.15.7 TypeError: Cannot read properties of undefined (reading 'state') HistoryCardState.getFormattedLabelName (/hacsfiles/history-explorer-card/history-explorer-card.js:9:6254) HistoryCardState.newGraph (/hacsfiles/history-explorer-card/history-explorer-card.js:9:15753) HistoryCardState.addGraphToCanvas (/hacsfiles/history-explorer-card/history-explorer-card.js:9:34975) HistoryCardState.addFixedGraph (/hacsfiles/history-explorer-card/history-explorer-card.js:9:31851) HistoryCardState.createContent (/hacsfiles/history-explorer-card/history-explorer-card.js:70:4090) HistoryCardState.updateContent (/hacsfiles/history-explorer-card/history-explorer-card.js:70:6734)
```

**Comment by alexarch21** [comment]
HA version, history explorer card version ?

**Comment by mobiledude** [comment]
HA Version: Home Assistant 2023.10.0b4
Frontend-versie: 20230928.0 - latest
HEC version : v1.0.50

```
  - card_mod:
      class: top-level-card
      style: |
        ha-card {
          text-align: center;
        }
    type: custom:sankey-chart
    show_names: true
    wide: true
    round: 0
    height: 40
    unit_prefix: m
    energy_date_selection: false
    sections:
      - entities:
          - entity_id: sensor.gas_m_3_plafond_huidige_maand
            name: m³ Plafond
            color: '#f0563e'
            children:
              - sensor.dsmr_current_month_gas
              - sensor.resterend_gas_m3_plafond_huidige_maand
      - entities:
          - entity_id: sensor.dsmr_current_month_gas
            name: Verbruik
          - entity_id: sensor.resterend_gas_m3_plafond_huidige_maand
            name: m³ Restant
            color: green
    template_data:
      columns: 3
    ll_data:
      columns: 3
  - axisAddMarginMin: false
    cardName: historycard-45127706
    combineSameUnits: true
    defaultTimeRange: 1d
    graphs:
      - entities:
          - color: '#f99501'
            entity: sensor.dsmr_consumption_gas_currently_delivered
            name: Gas
          - color: '#1e9af4'
            entity: sensor.water_meter_kit_water_meter_kit_total_consumption
            name: Water
        options:
          interval: daily
        type: bar
    header: hide
    labelAreaWidth: 7
    labelsVisible: false
    stateColors:
      schedule.on: grey
    stateTextMode: true
    statistics:
      enabled: true
      mode: mean
    showCurrentValues: true
    type: custom:history-explorer-card
    uiColors:
      buttons: rgba(255,255,255,255,0.0)
    uiLayout:
      selector: hide
      toolbar: true
```
