### ISSUE TITLE
Is it possible to configure as a HA Custom Panel?

### ISSUE THREAD

**Issue by deepcoder** [alexarch21/history-explorer-card#21]
1st, thanks for your work! Useful card!

I tried to add History Explorer to the side panel, based on the config I had for another panel. However, I just end up with a blank window. Is configuring in this manner possible? If so, I'm sure I'm doing it wrong. Your thoughts? Thx.

```
# configuration.yaml

lovelace:
  mode: yaml
  resources:
    # https://github.com/alexarch21/history-explorer-card
    - type: module
      url: /local/history-card/history-explorer-card.js

panel_custom:
  - name: history-explorer-card
    sidebar_title: History Explorer
    sidebar_icon: mdi:clipboard-text-clock
    url_path: history-explorer
    module_url: /local/history-card/history-explorer-card.js
    trust_external_script: true
```

https://www.home-assistant.io/integrations/panel_custom/

**Comment by alexarch21** [comment]
Good question, I never tried. It might need some specific code in the JS to work. I'll see if I can make this work, could be useful.

**Comment by alexarch21** [comment]
I got it to work. It requires some minor changes to the card code, as HA manages card config differently with panels for some reason (which, as usual, is not documented...). I'll add panel support in the next version.

**Comment by alexarch21** [comment]
Panel mode support was added in v1.0.19. You will have to supply the card config (if you need any) under the panel_custom settings in configuration.yaml, for example like this:

```yaml
panel_custom:
  - name: history-explorer-card
    url_path: redirect-server-controls
    sidebar_title: History Explorer
    sidebar_icon: mdi:server
    module_url: /local/hec/history-explorer-card.js
    config:
      header: 'Panel test'
      graphs:
        - type: line
          entities:
            - entity: sensor.outside_temperature
              color: '#3e95cd'
              fill: 'rgba(151,187,205,0.15)'
            - entity: sensor.annexe_temperature
              color: '#ee3452'
```
Every change to the YAML config requires a complete restart of HA (!). Not very user friendly, but there's nothing I can do about this sadly. Dynamic configuration works on the fly in the same way it does when used as a card.
