### ISSUE TITLE
Auto coloring based on class

### ISSUE THREAD

**Issue by Pulpyyyy** [alexarch21/history-explorer-card#210]
Hi,

I'm trying to rationalize the different cards under HA, and I'm doing some tests with explorer-card.
I think I figured out from the documentation how to apply color to entities based on type, but I can't seem to implement it.

Anglais
Sur cette exemple aucune des 3 couleurs ne s'applique et pourtant l'attribut existe bien dans les entités
In this example none of the 3 colors apply and yet the attribute does exist in the entities
![image](https://github.com/alexarch21/history-explorer-card/assets/32004297/df3ebc1e-fbb7-4e95-b3db-4a339389ee6d)
```
type: custom:history-explorer-card
cardName: historycard-49155611
entityOptions:
  temperature:
    color: pink
  humidity:
    color: purple
  illuminance:
    color: magneta
graphs:
  - type: line
    entities:
      - entity: sensor.sonde_jardin_temperature
  - type: line
    entities:
      - entity: sensor.sonde_jardin_humidite
  - type: line
    entities:
      - entity: sensor.sonde_salon_illuminance_lux
```
![image](https://github.com/alexarch21/history-explorer-card/assets/32004297/43c040db-2635-4bd2-a85c-34467a47c70b)

Is it a bug  or am i missing something ?

Regards

**Comment by alexarch21** [comment]
La clé `entityOptions` ne s'applique qu'aux entités que tu ajoutes par l'UI, donc en dynamique. Toi tu as défini tes graphiques par le yaml, donc cette clé ne s'applique pas à ton cas. Tu devras préciser les couleurs manuellement par graphique (`color` et optionellement `fill` sous chaque clé `entity`, y a des exemples dans le [readme ici](https://github.com/alexarch21/history-explorer-card#yaml-configuration-for-preconfigured-graphs)).

En gros, si tu défini tes graphs avec les yaml tu demandes à la carte que tu veux prendre le contrôle total manuel sur ta config. Donc tu dois tout préciser (enfin presque tout, il a certaines valeurs appliquées par défaut). Si tu veux que la carte prenne tout en main, utilises l'UI.

**Comment by Pulpyyyy** [comment]
Merci pour ce retour.
C'est dommage de ne pas pouvoir utiliser les options de colorisation automatiques avec le mode YAML.
C'est justement ce que j'espérai : en combinant cette carte avec https://github.com/custom-cards/decluttering-card, j'aurai pu faire un template avec les couleurs définies une seule fois
Par exemple : 
```
  explorer_generic:
    element:
      type: custom:history-explorer-card
      cardName: historycard-[[id]]
      entityOptions:
        temperature:
          color: blue
        humidity:
          color: orange
        illuminance:
          color: green
      recordedEntitiesOnly: true
      defaultTimeRange: '[[show]]h'
      combineSameUnits: false
      header: hide
      uiLayout:
        toolbar: bottom
        selector: hide
      graphs:
        - type: line
          entities: '[[entities]]'
```
 et indiquer uniquement les entités. Les couleurs auraient été toujours homogènes dans mes Dashboard.
```
          type: custom:decluttering-card
          template: explorer_generic
          variables:
            - id: 543545
            - show: 72
            - entities:
                  - entity: sensor.sonde_jardin_temperature
                    name: Température
                  - entity: sensor.sonde_jardin_humidite
                    name: Humidité
```
J'imagine que c'est la même chose pour combineSameUnits ?
