### ISSUE TITLE
Set a different baseline in y-axis for the fill area. Positive/negative reference starting from 32.

### ISSUE THREAD

**Issue by sdrapha** [alexarch21/history-explorer-card#220]
Is it possible to set the baseline of the Fill area not to be Zero? I would like to have the fill areas coming out of 32 (°F)

If you see my chart, I think it's easy to understand my goal, having 32 as the splitting point.

![image](https://github.com/alexarch21/history-explorer-card/assets/25059996/747623f6-8e90-4f0a-b3b9-76cec208984e)

<details>
<summary>Click to expand card yaml configuration</summary>

```yaml

type: custom:history-explorer-card
cardName: historycard-isdfk932990234
header: hide
uimode: dark
uiLayout:
  toolbar: bottom
  selector: hide
refresh:
  automatic: true
combineSameUnits: true
showCurrentValues: true
axisAddMarginMin: false
axisAddMarginMax: false
lineMode: stepped
legendVisible: true
defaultTimeOffset: 0.5h
defaultTimeRange: 24h
graphs:
  - type: line
    options:
      showSamples: false
    entities:
      - entity: sensor.mocreo_garage_fridge
      - entity: sensor.mocreo_garage_freezer
      - entity: sensor.mocreo_chest_freezer
```

</details>
