### ISSUE TITLE
how to round to an integer?

### ISSUE THREAD

**Issue by EaglePPP** [alexarch21/history-explorer-card#230]
Hello dear developer and maintainers,

i love this plugin, I have been using it for about a year now.

So now I have been wanting to implement a card which includes the uv index of my area .
The problem now is I haven't been able to use the integer to express the uv index.
What I want is just 0,1,2,3,4 but no decimal at all
I have tried rounding: -1, 0 they dont make it to integer

Could anyone tell me how to achieve that?
Thank!
here is my yaml

```
type: custom:history-explorer-card
header: ' '
defaultTimeRange: 6h
defaultTimeOffset: 1h
rounding: 1
recordedEntitiesOnly: true
showCurrentValues: true
refresh:
  automatic: true
graphs:
  - type: line
    options:
      ymin: 0
      ymax: 10
      ystepSize: 1
    entities:
      - entity: sensor.openuv_current_uv_index
        scale: 1
uiLayout:
  toolbar: top
  selector: hide
```
