### ISSUE TITLE
Blank graph

### ISSUE THREAD

**Issue by Lockie85** [alexarch21/history-explorer-card#240]
Hi,

My previously working card has stopped displaying any information and looks like so:
![image](https://github.com/alexarch21/history-explorer-card/assets/7091582/746fd573-0fb2-450b-9d3e-7bec395ec87f)

The code behind it is:
```
type: custom:history-explorer-card
graphs:
  - type: line
    entities:
      - entity: sensor.bedroom_1_temperature_and_humidity_sensor_4
      - entity: sensor.bedroom_2_temperature_and_humidity_sensor_3
      - entity: sensor.bedroom_3_temperature_and_humidity_sensor_2
      - entity: sensor.bedroom_4_temperature_and_humidity_sensor
      - entity: sensor.thermostat_temperature
      - entity: sensor.weather_station_temperature
```

Do you see any issues with that is defined?

Many Thanks
