### ISSUE TITLE
Yaml graphs don't have any colors

### ISSUE THREAD

**Issue by PD75** [alexarch21/history-explorer-card#30]
![image](https://user-images.githubusercontent.com/10294795/162370513-129ba556-5429-42f2-859c-3c555300ce23.png)
```
type: custom:history-explorer-card
cardName: advanced-history
uimode: dark
stateColors:
  person.home: blue
  person.not_home: yellow
decimation: false
header: My sample history
graphs:
  - type: line
    entities:
      - entity: sensor.bathroom_switch_battery_level
      - entity: sensor.tradfri_motion_sensor_battery_level
      - entity: sensor.double_switch_battery_level
```
