### ISSUE TITLE
Wildcard entity selection

### ISSUE THREAD

**Issue by RogerSelwyn** [alexarch21/history-explorer-card#47]
It would be great if a wildcard could be used for entity selection such as 'device_tracker.*'. Even better if there were exclusions as well. With the core history panel being massively changed, the capability to do this level of entity selection would substantially fill the gap left by the core changes.

Thanks

**Comment by alexarch21** [comment]
Sounds like a good idea.

**Comment by alexarch21** [comment]
Now available in V1.0.23 !

Examples:
`person.*` - Adds all entities from the person domain
`*door*` - Adds all entities that contain the term 'door' in the name, regardless of domain
`binary_sensor.*door*` - Adds all entities that contain the term 'door' in the name, but only from the binary_sensor domain
`*` - Adds all entities. Everything. Careful with that ;)

There's a new option in the selector dropdown menu to remove all dynamically added graphs in one go and start over.

**Comment by RogerSelwyn** [comment]
This is great, and I'll give it a go straightaway. Is there the possibility of an exclude as well? So add all device_tracker.*, but exclude device_tracker.foobar*?

**Comment by alexarch21** [comment]
No exclude yet. You can always remove it with the close button once added. The final selection is stored in the browser cache, as usual.

**Comment by RogerSelwyn** [comment]
I get 'undefined' when I use 'device_tracker.*' with latest release

**Comment by alexarch21** [comment]
Screenshot please ?

**Comment by RogerSelwyn** [comment]
I can do it dynamically, but not via YAML. I have various graphs setup for monitoring which I want to be the same across all devices, so I setup via yaml. I setup like this:

```
type: custom:history-explorer-card
header: ' '
cardName: historycard-64915052
labelAreaWidth: 100
combineSameUnits: true
defaultTimeRange: 6
showUnavailable: false
graphs:
  - type: timeline
    entities:
      - entity: binary_sensor.tyrcelyn_utility_motion
      - entity: binary_sensor.tyrcelyn_presence_all
      - entity: binary_sensor.tyrcelyn_booking
      - entity: binary_sensor.internet
      - entity: binary_sensor.garage_cam
      - entity: binary_sensor.workshop_cam
      - entity: sensor.sky_media_playing
      - entity: media_player.tyrcelyn_tctv
      - entity: sensor.tv_media_playing
      - entity: binary_sensor.bluray
      - entity: sun.sun
      - entity: weather.ty_r_celyn
      - entity: device_tracker.*
```
