### ISSUE TITLE
Feature Request: Enable customization of timeline colors for sensors

### ISSUE THREAD

**Issue by LeapFrogSupport** [alexarch21/history-explorer-card#48]
History Explorer is an outstanding contribution to Home Assistant.  It is far superior to the History panel kludge that was released in the 2022.7 core update.

Here's an feature that I think would be very useful ---

I have a template sensor derived from a binary_sensor for our garage door:
 
```
 - platform: template
    sensors:
      garage_door_status:
        friendly_name: 'Garage Door Status'
        unique_id: "Garage Door Status"
        value_template: >-
          {% if is_state('binary_sensor.garage_door_tilt_sensor_access_control_window_door_is_open', "on") %}Open{% else %}Closed{% endif %}
```
It would be advantageous to enable the ability to change the default timeline bar colors for the template sensor for an entity.  In my case, when the garage_door_status sensor state is Closed, the timeline color is red, and when it is Open the color is purple.  This feature would enable the user to customize these colors.  I suggest something similar to the domain color features for switch.on / off and light.on / off that would be applied at the entity level.

```
stateColors:
  switch.off: silver
  switch.on: red    
  ........
# FR: Would like to be able to do
#  sensor.garage_door_status.open: red
#  sensor.garage_door_status.closed: green
```
Screenshot of my current History Explorer panel is attached. 

![Screenshot 2022-07-23 at 09-31-43 History Explorer – Home Assistant](https://user-images.githubusercontent.com/625467/180607306-f8c779d6-4d76-485f-8f80-05a2d9dc418a.png)
