### ISSUE TITLE
Feature request: automatic colors for preconfigured graphs

### ISSUE THREAD

**Issue by denilsonsa** [alexarch21/history-explorer-card#52]
When interactively adding entities to the history explorer card, it is smart enough to pick colors automatically. However, for preconfigured graphs, the card doesn't work properly until the user manually sets each specific color in the YAML configuration. That shouldn't be required, the colors should be automatic when omitted.

---

See this screenshot of the built-in history card compared to the custom history explorer card.

![image](https://user-images.githubusercontent.com/121676/181341686-9aadfcfa-dcf1-45fe-be8b-08ecc6d7de1d.png)

```yaml
type: custom:auto-entities
card:
  type: history-graph
  hours_to_show: 48
filter:
  include:
    - entity_id: climate.living_room
    - entity_id: sensor.ble_temperature*
  exclude: []
sort:
  method: none
```

```yaml
type: custom:history-explorer-card
cardName: historycard-alltemperatures
combineSameUnits: true
uiLayout:
  selector: hide
graphs:
  - type: line
    entities:
      - entity: sensor.ble_temperature_alpha
      - entity: sensor.ble_temperature_beta
      - entity: sensor.ble_temperature_gamma
      - entity: sensor.ble_temperature_delta
      - entity: sensor.ble_temperature_epsilon
      - entity: sensor.living_room_temperature
```
