### ISSUE TITLE
FR: Allow theme colors

### ISSUE THREAD

**Issue by VDRainer** [alexarch21/history-explorer-card#6]
If i use theme variables in the configuration.

theme.yaml
```
  # My colors
  my-blue: "#55acee"
  my-green: "#9bc53d"
  my-yellow: "#fde74c"
  my-red: "#c3423f"
```
config
```
    - type: line
      entities:
        - entity: sensor.ds18b20_01
          name: Temp one
          color: var(--my-green)
          #color: "#55acee"
        - entity: sensor.ds18b20_02
          name: Temp two
          color: var(--my-yellow)
          #color: "#55acee"
```
it shows this:
![20220121_224443](https://user-images.githubusercontent.com/26381449/150604283-9e0614e3-d021-4c5c-8702-fafc8530f474.png)

Thanks for this wonderfull card!
