### ISSUE TITLE
Regression with explicitly defined fill colours

### ISSUE THREAD

**Issue by RogerSelwyn** [alexarch21/history-explorer-card#62]
The following no longer results in a fill with no line for sensor.nest_heating, instead a line is generated. Reverting to 1.0.23 solves the problem. 1.0.24 introduces the problem.

```
- type: line
    options:
      ymin: 0
    entities:
      - entity: sensor.nest_current_temperature
        lineMode: curves
        name: Current
        color: '#84bb7199'
      - entity: sensor.nest_set_temperature
        lineMode: stepped
        name: Set
        color: '#6592eb'
      - entity: sensor.nest_heating
        lineMode: stepped
        name: Heating
        fill: '#84bb7199
```
