### ISSUE TITLE
Incorrect margin-top value for YAML defined bar charts

### ISSUE THREAD

**Issue by alexarch21** [alexarch21/history-explorer-card#65]
Incorrect margin-top value for YAML defined bar charts ?

**Comment by emufan** [comment]
O.k. here we go. I removed the overhead and it seems that it only occuring, if placed in a custom:vertical-stack-in-card

```
type: custom:vertical-stack-in-card
cards:
  - type: custom:history-explorer-card
    graphs:
      - type: bar
        entities:
          - entity: sensor.hausenergiezahler_energy_counter
```

But here as well only for yaml-setup. If I add energy sensors in UI, it is working as you are expecting.
