### ISSUE TITLE
stateColors for input_number

### ISSUE THREAD

**Issue by YvesZH** [alexarch21/history-explorer-card#73]
Thanks for the great card 👏👍

I like to have for my input numbers the following state Colors:
0=red 
1-99= orange
100=green

my config (part of it):
```
       stateColors:
          switch.on: green
          switch.off: red
          light.on: green
          light.off: red
          script.on: green
          script.off: red
          input_boolean.on: green
          input_boolean.off: red
          binary_sensor.on: green
          binary_sensor.off: red
          input_number: orange
          input_number.0: red
          input_number.100: green
```

but just looks like:
![E5CE47C2-02A1-4730-9458-F211C6DAB50D](https://user-images.githubusercontent.com/64573990/196646421-de10aae2-0404-44c0-8848-cdb404180b1c.jpeg)

How can i do this?
Thanks
