### ISSUE TITLE
Enhancement: add min/ max values

### ISSUE THREAD

**Issue by haaino** [alexarch21/history-explorer-card#77]
Hi,

Thank you for the great job until now! Very useful tool!

Would it be possible to create an option that displays in the graph the min and/ or maximum value?

Best regards
Haaino

**Comment by alexarch21** [comment]
What exactly do you mean by this?

**Comment by haaino** [comment]
<img width="525" alt="Screenshot 2022-10-23 at 13 26 44 " src="https://user-images.githubusercontent.com/98317278/197389466-d3df5118-2698-423a-852c-e159c14ddc9e.png">

Sure. See attached screen capture.

**Comment by alexarch21** [comment]
Okay. I'll mark this as an FR.

**Comment by JanDetrez** [comment]
Hi

I think I would like to see the same thing. I want to extract daily min/max values

The raw data is this
![image](https://github.com/alexarch21/history-explorer-card/assets/16916740/6ac31c48-35bd-420a-8d87-865358175b4c)


But when going to bar, it averages only. Would be nice to select to view min/max
![image](https://github.com/alexarch21/history-explorer-card/assets/16916740/498e1fc9-472b-42f0-a97f-27eabaf9cefd)


```
statistics:
  enabled: true    # true is the default, use false to turn LTS support off.
  mode: mean
  period: hour     # reporting period. hour, day or month. Default is hour.
```
This I tested, but it is not related to this request.


Another (slightly related) issue I have is when going monthly, it will sum values. It's not clear to me how to keep the graph to averaging values, rather than summing
![image](https://github.com/alexarch21/history-explorer-card/assets/16916740/b5a6b4b6-956e-4d4d-8a92-7b8a0fb4d474)

This doesn't help
```
graphs:
  - type: bar
    options:
      interval: monthly
```
