### ISSUE TITLE
Configured Interval on total increasing bar chart not working

### ISSUE THREAD

**Issue by rct** [alexarch21/history-explorer-card#81]
If I set `interval: daily` on a total increasing bar chart it seems to be ignored, but it works when set through the drop down. (Maybe I'm doing something wrong or not understanding the README?).

Edit: I tried this with both 1.0.29 and 1.0.31.

```
type: custom:history-explorer-card
cardName: historycard-solar-daily-38508067
header: Solar Daily Production
defaultTimeRange: 2w
interval: daily
graphs:
  - type: bar
    interval: daily
    entities:
      - entity: sensor.envoy_lifetime_energy_production
      - entity: sensor.envoy_json_production_lifetime
  - type: bar
    interval: daily
    entities:
      - entity: sensor.envoy_inverter_panel_1_energy
  - type: bar
    interval: daily
    entities:
      - entity: sensor.envoy_inverter_panel_2_energy
```

**Comment by alexarch21** [comment]
As described in the readme [here](https://github.com/alexarch21/history-explorer-card#bar-graphs-for-total-increasing-entities), the interval setting has to go under the `options` key.
```
graphs:
  - type: bar
    options:
      interval: daily
```

**Comment by rct** [comment]
I didn't see that example and didn't think it was related because this paragaph and example YAML is in between the text and relevant example:  

```
Example configuration of a bar chart display for the entity `sensor.rain_amount` when added dynamically. The default interval is 10 minutes and the type is explicitly set to `bar`. The latter is not needed if the entity has a `total_increasing` state class.

  ```yaml
  entityOptions:
    sensor.rain_amount:
      type: bar
      color: '#3e95cd'
      interval: 10m     # Default interval for this entity can be 10m, hourly or daily
  ```
```

I think the above paragraph about entity options and YAML needs to move so it doesn't break up the graph options related text from the example YAML.

Also I'm not sure what that sentence "Example configuration of a bar chart display for the entity `sensor.rain_amount` when added dynamically" is supposed to be saying.
