### ISSUE TITLE
Automatic Y-Axis min/max does not work

### ISSUE THREAD

**Issue by N3rdix** [alexarch21/history-explorer-card#92]
I have some charts on my 2022.10.5 system with a defaultTimeRange of 30min and it seems the Y-axis automatic scaling does not work as expected. When zooming out (larger time frame) the y-max makes sense, so I am wondering if this is a bug?

I would assume the max to be adjusted in the following example to something around 100W, but in the browser console I can see that data for the whole day is selected and might be the basis four calculating min/max:
`http://<IP>:8123/api/history/period/2022-11-14T00:00:00?end_time=2022-11-15T00:00:00...`

Navigating in with default setting:
![image](https://user-images.githubusercontent.com/70015952/201657672-5741d8a7-5cf6-445b-907d-6b207fa1661d.png)

Zooming out:
![image](https://user-images.githubusercontent.com/70015952/201657805-ff44b021-9a8c-4a4b-9cd6-6a34820e9dc1.png)

Card YAML
```
type: custom:history-explorer-card
cardName: historycard-35447551
filterEntities: sensor.*
header: hide
combineSameUnits: true
lineMode: stepped
defaultTimeRange: 30m
decimation: false
axisAddMarginMin: true
axisAddMarginMax: true
graphs:
  - type: line
    entities:
      - entity: sensor.heizung_leistung_ehs_aktuell
      - entity: sensor.aktuelle_leistung_heizung_shelly
```
