### ISSUE TITLE
infopanel iOS glitches

### ISSUE THREAD

**Issue by emufan** [alexarch21/history-explorer-card#94]
1. Line color change when in future and on day breaks

![image](https://user-images.githubusercontent.com/22775515/202740217-2d1f8b58-52d3-4c81-a378-e512a729c83d.png)

The line is not hidden (as thought first), but in black instead of blue the rest of the time.

Tt is not only happening reproducable when moving to the end/future, but on every day-break as well. The same spot, where desktop chrome is changing the auto-zoom in the background before releasing the mouse button. In this spot, the line is black and stays black if I release my finger in this sport. If I more a little bit more in the days before or current day, the line is blue and stays blue if I release there. See video with some examples.

![27c2fcc15d40a7fc1baeea376bce403b27c8177b](https://user-images.githubusercontent.com/22775515/202740374-efee0cd1-258b-46f5-a8fb-a89b76ec5986.gif)

2. iOS sometimes shows the additional line within the timeline chart, which his hidden elsewhere (and on iOS in the cases where it is shown on iOS).

![image](https://user-images.githubusercontent.com/22775515/202740914-9a12a14e-8184-4e2f-9ec2-49189018cb7d.png)

Here I have not seen other helpfull information. Gut feeling: Not that often anymore not hidden and visible. Even on the same entity, the line is there or not. Sometime 10 in a row not there and only on opening the 11th time. Sometimes on 2nd opening already ann on 3rd gone again. :see_no_evil:

Besides: It is directly hidden, when initially not hidden on open, if I start dragging.

**Comment by emufan** [comment]
Update for 2. It appears together with the popup as well. And disappears after pointing elsewhere to hide the tooltip again.

**Comment by emufan** [comment]
Here is my yaml for the infopanel

```
infoPanel:
  lineMode: stepped
  uimode: dark
  showUnavailable: false
  uiColors:
    gridlines: '#212121'
    labels: '#BAC0C6'
    buttons: '#2e2e2e'
    selector: '#2e2e2e'
  statistics:
    enabled: true
    mode: mean
  tooltip:
    size: compact
    showColorsLine: false
    showColorsTimeline: false
    showDuration: true
    showLabel: false
```

**Comment by emufan** [comment]
As always: Not urgent or time critical ... 

If I should test something or you need further details, just give me a ping.

**Comment by alexarch21** [comment]
I did some more tests on an iOS emulator and could not reproduce this. I found someone with an actual iPhone and it did not show this problem either. So at this point I am not sure how to reproduce this at all.

**Comment by emufan** [comment]
As I have it really everywhere and always, I started further test. Let's first focus on the additional (aka not hidden middle-line).

![image](https://user-images.githubusercontent.com/22775515/205241636-c35a6cb8-0b24-4d19-acbf-904f02a9f488.png)

With only this config for example and defintion

```
type: custom:history-explorer-card
infoPanel:
  lineMode: stepped
cardName: history-explorer-card-999
defaultTimeRange: 1d
lineMode: stepped
graphs:
  - type: timeline
    entities:
      - entity: sun.sun
  - type: line
    entities:
      - entity: sensor.hausenergiezahler_power
  - type: bar
    entities:
      - entity: sensor.hausenergiezahler_energy_counter
```

Then the middle line (and the most left vertical one) are back on iOS always. In chart and infopanel. But perhaps depending on the time of the day. I'll just saw this and come to this later.

And they disappear **always** on tooltip. In chart and infopanel. And re-appear (most of the time) on leaving tooltip. In chart and infopanel.

BTW OT: Regarding the other issues form yesterday. infopanel shows different states as chart. Chart is showing raw by default. Infopanels is showing auto by default. But not relevant for this here.

https://user-images.githubusercontent.com/22775515/205242849-b86fa36c-08e0-4aca-82ec-db61ce3cb802.mov

https://user-images.githubusercontent.com/22775515/205242979-369f0e28-c0b6-4e2f-b7c9-d4600e6ff72b.mov

If I disable showColorsTimeline, so change the above config to

```
type: custom:history-explorer-card
infoPanel:
  lineMode: stepped
  tooltip:
    showColorsTimeline: false
cardName: history-explorer-card-999
lineMode: stepped
tooltip:
  showColorsTimeline: false
defaultTimeRange: 1d
graphs:
  - type: timeline
    entities:
      - entity: sun.sun
  - type: line
    entities:
      - entity: sensor.hausenergiezahler_power
  - type: bar
    entities:
      - entity: sensor.hausenergiezahler_energy_counter
```

The middleline and most left vertical one are **always** shown when tooltip is shown. In chart and infopanel. This was already the case

https://user-images.githubusercontent.com/22775515/205244909-f1323a18-9433-4df7-b2c6-9035e51d9770.MP4

And no I come to the come to the later from above. Regarding time of the day. And mentioned some posts above, they disappear on moving the timeline. And perhaps this is the clue and this is perhaps the correlation to the other problem as well. It is shown, when in the future on the right side or if you are on a day-break on the left or right side (don't know what is relevant). And hidden again, if you have not daybreak (with bold day date) in the visible area. But I can only reproduce this in portrait mode. Line in future is with portrait and landscape and on ipad and iphone, but line on day break only in portrait on iphone. So the "futureline" is the most stable. 

Update on this. Perhaps related if a state text is shown or not? So future and day break only by chance. Don't know and therefor I didn't remove my text before.

https://user-images.githubusercontent.com/22775515/205248141-05f9b626-7d8d-4379-bb65-869c801935a2.MP4

But this is not correlated to the shown behavior above, that it is always shown together with a tooltip and disabled showColorsTimeline and always hidden together with a tooltip and enabled showColorsTimeline.

**Comment by alexarch21** [comment]
Okay, I was able to test this on another iPhone recently. It doesn't show this behavior either. Is there anyone else here or on the HA forums that experienced this besides you ? I haven't heard of anyone else and I assume that there must be several people using this on iOS. For the iOS layout issues with the toolbar a while ago, there were reports from multiple people.

I'm wondering if this is somehow related to a specific setting or config option within iOS or Safari that you use, but most people don't. You mentioned this happened on multiple i* devices you have. Are they all running the same version of iOS, Webkit and Safari ? Are you using the HA iOS app ? If yes, is it happening both on the app and on Safari ?

**Comment by emufan** [comment]
I trust in your tests 👍, but it is very suspicious. Because I can reproduce this 100% on not only some but every i* device and every ha server. Just did it

- on two iphones and two ipads.
- two different ha instances. Just set up an old version 2022.8.7 instead of the other 2022.11.5
- in every theme, even without theme
- happening in app and safari
- no special advanced settings

The line (focus currently still only on the middle-line in timeline) is even there in standard chart not only in info panel. 

And exactly as described above. 

- Line is always (and really always) there if I scroll somewhere, where no state test is displayed, e.g. in the future, but in cases without text in the past as well.
- Line is always there with active tooltip with `tooltip: showColorsTimeline: false` and always hidden with active tooltip and `tooltip: showColorsTimeline: true`

Did you really test with the simplified cases above

```
type: custom:history-explorer-card
cardName: history-explorer-card-999
tooltip:
  showColorsTimeline: false
graphs:
  - type: timeline
    entities:
      - entity: sun.sun
```

and scrolled to the future and touched a state (active tooltip) with showColorsTimeline:false?
